menu:
  # - date: 
  #   url: 'date'
  #   title: '日期'
  # - archive: 
  #   url: 'list'
  #   title: '归档'
  # - tag: 
  #   url: 'tags'
  #   title: '标签'
  # - category: 
  #   url: 'categories'
  #   title: '分类'
  # - search: 
  #   url: 'search'
  #   title: '搜索'

# algolia:
#   appId: ""
#   apiKey: ""
#   indexName: ""

# staticman: 