menu:
  - archive: 
    url: 'archives'
    title: 'archive'
    icon: 'archive'
  # - date: 
  #   url: 'date'
  #   title: 'date'
  #   icon: 'date'
  # - tag: 
  #   url: 'tags'
  #   title: 'tag'
  #   icon: 'tag'
  # - category: 
  #   url: 'categories'
  #   title: 'category'
  #   icon: 'category'
  # - search: 
  #   url: 'search'
  #   title: 'search'
  #   icon: 'search'

# algolia:
#   appId: ""
#   apiKey: ""
#   indexName: ""

# staticman: 