menu:
  - home: 
    url: ''
    title: 'homepage'
    icon: 'home'
  # - date: 
  #   url: 'date'
  #   title: 'date'
  #   icon: 'date'
  # - archive: 
  #   url: 'archives'
  #   title: 'archive'
  #   icon: 'archive'
  # - tag: 
  #   url: 'tags'
  #   title: 'tag'
  #   icon: 'tag'
  # - category: 
  #   url: 'categories'
  #   title: 'category'
  #   icon: 'category'
  # - search: 
  #   url: 'search'
  #   title: 'search'
  #   icon: 'search'

# algolia:
#   appId: ""
#   apiKey: ""
#   indexName: ""

# tapir_token: 

# staticman: 

# highlight_theme: 
