highlight_theme: atom-one-dark

# date: true

# archive: true

# tags: true

# categories: true

# github: 

# email: 

# algolia:
#   appId: ""
#   apiKey: ""
#   indexName: ""

# tapir_token: 

# duoshuo: 

# disqus: 

# staticman: 